spring.application.name=inv_backend

spring.datasource.url=jdbc:postgresql://postgres:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.cache.type=redis
spring.cache.redis.time-to-live=60s
logging.level.org.springframework.cache=TRACE